package jobs

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
)

// Per-job grok sandbox profile (`<handoff>/.grok/sandbox.toml`).
//
// The built-in `workspace` profile reads everywhere but writes only to cwd,
// /tmp and ~/.grok — so `simctl install` (which writes into the CoreSimulator
// device tree) fails, and an agent can only produce widget renders instead of
// real on-device screenshots. grok supports custom profiles that extend a
// built-in one with extra `read_write` grants; DD writes one into the handoff
// so the grant is scoped to a single job and never edits the operator's global
// ~/.grok/sandbox.toml.
//
// Opt-in per app (App Settings → Simulator writes). Default off: this widens
// what a coding agent may modify on the host.

func simulatorDevicesDir() string {
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		home = os.Getenv("HOME")
	}
	return filepath.Join(home, "Library", "Developer", "CoreSimulator", "Devices")
}

// SandboxProfileResult is the --sandbox name plus prompt notes.
type SandboxProfileResult struct {
	Profile string
	Notes   []string
}

const simulatorProfileName = "dd-simulator"

// writeSimulatorSandboxProfile writes a job-scoped profile granting Simulator
// writes on top of base (`workspace` or `strict`). read_write takes literal
// directory grants (no globs). Never creates or edits ~/.grok/sandbox.toml.
func writeSimulatorSandboxProfile(handoffAbs, base, batchID string) (SandboxProfileResult, error) {
	if base != "workspace" {
		base = "strict"
	}
	devices := simulatorDevicesDir()
	dir := filepath.Join(handoffAbs, ".grok")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return SandboxProfileResult{}, err
	}
	extends, _ := json.Marshal(base)
	rw, _ := json.Marshal(devices)
	body := strings.Join([]string{
		"# Generated by Defect Drainer for " + batchID + " — job-scoped, not global.",
		"[profiles." + simulatorProfileName + "]",
		"extends = " + string(extends),
		"read_write = [" + string(rw) + "]",
		"",
	}, "\n")
	if err := os.WriteFile(filepath.Join(dir, "sandbox.toml"), []byte(body), 0o644); err != nil {
		return SandboxProfileResult{}, err
	}
	return SandboxProfileResult{
		Profile: simulatorProfileName,
		Notes: []string{
			"SIMULATOR: this job may write to the iOS Simulator device tree (" + devices + ").",
			"- Real app installs/launches are allowed: prefer simctl screenshots of the running app over widget-test renders.",
			"- Nothing else on the host became writable.",
		},
	}, nil
}
