package jobs

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/joe/defect-drainer-go/internal/git"
)

// Pre-provision a writable Flutter toolchain inside the job handoff.
//
// Why: the `workspace` sandbox allows host *reads* but confines *writes* to the
// handoff cwd + temp. Flutter writes as it runs — `$FLUTTER_ROOT/bin/cache`,
// `$PUB_CACHE`, `$HOME/.dart-tool` — so an agent pointed at `~/fvm/versions/<pin>`
// cannot run `flutter test` at all. Observed 2026-08-17 in bjob_msws7z98_k8m9,
// where the agent hand-built a symlink SDK overlay to work around it and then
// verified the fix with widget renders instead of the project's real gate.
//
// The clone is APFS copy-on-write (`cp -Rc`): ~12s for a 2.0G SDK and near-zero
// disk until something diverges. It inherits the host SDK's already-populated
// `bin/cache`, so no download or precache step is needed.
//
// Never throws: a failed provision downgrades to "agent has no toolchain",
// which is the pre-existing behaviour, not a job failure.

// ToolchainProvision is extra env + prompt notes for a job-scoped SDK.
type ToolchainProvision struct {
	Env map[string]string
	// VerifyEnv is PATH for DD's unsandboxed runner. It must NOT include the
	// handoff clone: the agent can replace .tooling/bin after spawn.
	VerifyEnv map[string]string
	Notes     []string
	Ok        bool
}

// NO_TOOLCHAIN is the skip result.
var NO_TOOLCHAIN = ToolchainProvision{Env: map[string]string{}, Notes: []string{}, Ok: false}

var fvmPinRe = regexp.MustCompile(`^[A-Za-z0-9._-]+$`)

func readFvmPin(worktreeAbs string) string {
	raw, err := os.ReadFile(filepath.Join(worktreeAbs, ".fvmrc"))
	if err != nil {
		return ""
	}
	var doc struct {
		Flutter any `json:"flutter"`
	}
	if json.Unmarshal(raw, &doc) != nil || doc.Flutter == nil {
		return ""
	}
	pin := strings.TrimSpace(fmt.Sprint(doc.Flutter))
	if pin == "" {
		return ""
	}
	if !fvmPinRe.MatchString(pin) {
		return ""
	}
	return pin
}

func fvmVersionsRoot() string {
	if h := strings.TrimSpace(os.Getenv("FVM_HOME")); h != "" {
		return filepath.Join(h, "versions")
	}
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		return ""
	}
	return filepath.Join(home, "fvm", "versions")
}

func shJSON(v string) string {
	b, err := json.Marshal(v)
	if err != nil {
		return `""`
	}
	return string(b)
}

func writeFlutterShims(binDir, sdkDir, homeDir, pubCache string) error {
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return err
	}
	for _, tool := range []string{"flutter", "dart"} {
		body := strings.Join([]string{
			"#!/bin/sh",
			"# Generated by Defect Drainer — pre-provisioned toolchain for this job.",
			"export FLUTTER_ROOT=" + shJSON(sdkDir),
			"export PUB_CACHE=" + shJSON(pubCache),
			// HOME is redirected for the SDK only, so the agent's own ~/.grok stays put.
			"export HOME=" + shJSON(homeDir),
			"export FLUTTER_SUPPRESS_ANALYTICS=true",
			"exec " + shJSON(filepath.Join(sdkDir, "bin", tool)) + ` "$@"`,
			"",
		}, "\n")
		shim := filepath.Join(binDir, tool)
		if err := os.WriteFile(shim, []byte(body), 0o755); err != nil {
			return err
		}
	}
	return nil
}

func provisionFlutterToolchain(handoffAbs string, worktrees []git.WorktreeBinding, onLog verifyLog) ToolchainProvision {
	if onLog == nil {
		onLog = func(string, string) {}
	}
	type pinned struct {
		repo, abs, pin string
	}
	var found []pinned
	for _, w := range worktrees {
		if pin := readFvmPin(w.WorktreeAbs); pin != "" {
			found = append(found, pinned{w.Repo, w.WorktreeAbs, pin})
		}
	}
	if len(found) == 0 {
		onLog("toolchain=flutter but no worktree pins one (.fvmrc) — skipped", "warn")
		return NO_TOOLCHAIN
	}
	seen := map[string]struct{}{}
	var pins []string
	for _, p := range found {
		if _, ok := seen[p.pin]; ok {
			continue
		}
		seen[p.pin] = struct{}{}
		pins = append(pins, p.pin)
	}
	if len(pins) > 1 {
		onLog("toolchain: worktrees pin conflicting Flutter versions ("+strings.Join(pins, ", ")+") — skipped", "warn")
		return NO_TOOLCHAIN
	}
	pin := pins[0]
	root := fvmVersionsRoot()
	source := filepath.Join(root, pin)
	if !pathExists(source) {
		onLog("toolchain: Flutter "+pin+" is not installed on the host ("+source+") — skipped. Run `fvm install "+pin+"`.", "warn")
		return NO_TOOLCHAIN
	}

	tooling := filepath.Join(handoffAbs, ".tooling")
	sdkDir := filepath.Join(tooling, "flutter-sdk")
	homeDir := filepath.Join(tooling, "home")
	pubCache := filepath.Join(tooling, "pub-cache")
	binDir := filepath.Join(tooling, "bin")

	if err := os.MkdirAll(tooling, 0o755); err != nil {
		onLog("toolchain: provisioning failed — skipped ("+err.Error()+")", "warn")
		return NO_TOOLCHAIN
	}
	_ = os.MkdirAll(homeDir, 0o755)
	_ = os.MkdirAll(pubCache, 0o755)

	started := time.Now()
	// -c clones on APFS; cp falls back to a full copy elsewhere (slower, but correct).
	cp := exec.Command("cp", "-Rc", source, sdkDir)
	if out, err := cp.CombinedOutput(); err != nil {
		msg := strings.TrimSpace(string(out))
		if msg == "" {
			msg = err.Error()
		}
		onLog("toolchain: provisioning failed — skipped ("+msg+")", "warn")
		return NO_TOOLCHAIN
	}
	secs := time.Since(started).Seconds()

	if err := writeFlutterShims(binDir, sdkDir, homeDir, pubCache); err != nil {
		onLog("toolchain: provisioning failed — skipped ("+err.Error()+")", "warn")
		return NO_TOOLCHAIN
	}

	pctx, pcancel := context.WithTimeout(context.Background(), 180*time.Second)
	probe := exec.CommandContext(pctx, filepath.Join(binDir, "flutter"), "--version")
	pout, perr := probe.CombinedOutput()
	pcancel()
	if perr != nil {
		why := strings.TrimSpace(string(pout))
		if why == "" {
			why = perr.Error()
		}
		if i := strings.IndexByte(why, '\n'); i >= 0 {
			why = why[:i]
		}
		onLog("toolchain: provisioned SDK failed its probe — skipped ("+why+")", "warn")
		return NO_TOOLCHAIN
	}

	onLog(fmt.Sprintf("toolchain: Flutter %s cloned → %s in %.1fs (APFS clone, shims in .tooling/bin)", pin, sdkDir, secs), "info")
	hostPath := os.Getenv("PATH")
	return ToolchainProvision{
		Ok:        true,
		Env:       map[string]string{"PATH": binDir + ":" + hostPath},
		VerifyEnv: map[string]string{"PATH": filepath.Join(source, "bin") + ":" + hostPath},
		Notes: []string{
			"TOOLCHAIN: Flutter " + pin + " is pre-provisioned and writable for this job.",
			"- Run `flutter` / `dart` directly (shims at " + binDir + " are first on PATH).",
			"- Do NOT use `fvm`, install another SDK, or build an SDK overlay — writes to ~/fvm are blocked and unnecessary here.",
			"- The project's own test/analyze/gate commands are expected to run; report exit codes in fix-notes.",
		},
	}
}
